# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(160E0E)
$foreground = rgb(E9DBD2)
$color0 = rgb(3E3737)
$color1 = rgb(752B14)
$color2 = rgb(724626)
$color3 = rgb(B21507)
$color4 = rgb(90694E)
$color5 = rgb(A96053)
$color6 = rgb(91735E)
$color7 = rgb(D8C4B6)
$color8 = rgb(97897F)
$color9 = rgb(9C3A1B)
$color10 = rgb(985D33)
$color11 = rgb(ED1C0A)
$color12 = rgb(BF8C68)
$color13 = rgb(E1806E)
$color14 = rgb(C2997E)
$color15 = rgb(D8C4B6)
