# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DBDCDF
background         #273247
cursor             #8C7B6A

active_tab_foreground     #273247
active_tab_background     #DBDCDF
inactive_tab_foreground   #DBDCDF
inactive_tab_background   #273247

active_border_color   #DBDCDF
inactive_border_color #273247
bell_border_color     #B09C78

color0      #ADAEB2
color1		#B09C78
color2		#8B957F
color3		#839390
color4		#7D7B6C
color5		#827369
color6		#9D6754
color7		#695D48
color8		#A49170
color9		#EAD0A0
color10		#B9C7A9
color11		#AEC4C0
color12		#A6A590
color13		#AE998C
color14		#D18970
color15		#ECDFC7
